# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 55248a5b577d6b2051ec8d5b715f8b7643900895f940ffeee52c266023f688e91e429144106578c8b918da6f136bbe8ef0b49f0af37ef536407700f099fd11cb

test:
  secret_key_base: 81f8457b78335c14faa4aebc0bdce4829aa8816571471b2cf3730ce63c6581ae20f0d0b26f1c94de163255d7627e3b6867c826a0899497d1978cd81503ccae60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
